version: '3'
services:
  prismahotel:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysqlhotel
            user: root
            password: prisma
            rawAccess: true
            port: 3306
            migrations: true
            connectionLimit: 5
  mysqlhotel:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysqlhotel:/var/lib/mysql
volumes:
  mysqlhotel:
